version: 2

defaults: &defaults
  working_directory: ~/project/injets
  docker:
    - image: circleci/node:8.9.1

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-injets-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-injets-{{ .Branch }}-
            - v1-injets-
      - run: yarn
      - save_cache:
          key: v1-injets-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - injets

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/rep
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
